# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer.ui'
#
# Created by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1300, 833)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1301, 791))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.frame)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 80, 731, 51))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.DurationLabels_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.DurationLabels_2.setMargin(0)
        self.DurationLabels_2.setObjectName(_fromUtf8("DurationLabels_2"))
        self.preLabel_2 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.preLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.preLabel_2.setObjectName(_fromUtf8("preLabel_2"))
        self.DurationLabels_2.addWidget(self.preLabel_2)
        self.rinLabel_2 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.rinLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.rinLabel_2.setObjectName(_fromUtf8("rinLabel_2"))
        self.DurationLabels_2.addWidget(self.rinLabel_2)
        self.kyoLabel_2 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.kyoLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.kyoLabel_2.setObjectName(_fromUtf8("kyoLabel_2"))
        self.DurationLabels_2.addWidget(self.kyoLabel_2)
        self.tohLabel_2 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.tohLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.tohLabel_2.setObjectName(_fromUtf8("tohLabel_2"))
        self.DurationLabels_2.addWidget(self.tohLabel_2)
        self.shaLabel_2 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.shaLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.shaLabel_2.setObjectName(_fromUtf8("shaLabel_2"))
        self.DurationLabels_2.addWidget(self.shaLabel_2)
        self.kaiLabel_2 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.kaiLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.kaiLabel_2.setObjectName(_fromUtf8("kaiLabel_2"))
        self.DurationLabels_2.addWidget(self.kaiLabel_2)
        self.jinLabel_2 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.jinLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.jinLabel_2.setObjectName(_fromUtf8("jinLabel_2"))
        self.DurationLabels_2.addWidget(self.jinLabel_2)
        self.retsuLabel_2 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.retsuLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.retsuLabel_2.setObjectName(_fromUtf8("retsuLabel_2"))
        self.DurationLabels_2.addWidget(self.retsuLabel_2)
        self.zaiLabel_2 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.zaiLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.zaiLabel_2.setObjectName(_fromUtf8("zaiLabel_2"))
        self.DurationLabels_2.addWidget(self.zaiLabel_2)
        self.zenLabel_2 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.zenLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.zenLabel_2.setObjectName(_fromUtf8("zenLabel_2"))
        self.DurationLabels_2.addWidget(self.zenLabel_2)
        self.postLabel_2 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.postLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.postLabel_2.setObjectName(_fromUtf8("postLabel_2"))
        self.DurationLabels_2.addWidget(self.postLabel_2)
        self.sessionslidersLayout = QtGui.QWidget(self.frame)
        self.sessionslidersLayout.setGeometry(QtCore.QRect(10, 130, 761, 451))
        self.sessionslidersLayout.setObjectName(_fromUtf8("sessionslidersLayout"))
        self.DurationSliders_2 = QtGui.QHBoxLayout(self.sessionslidersLayout)
        self.DurationSliders_2.setMargin(0)
        self.DurationSliders_2.setObjectName(_fromUtf8("DurationSliders_2"))
        self.preSlider_2 = QtGui.QSlider(self.sessionslidersLayout)
        self.preSlider_2.setMaximum(90)
        self.preSlider_2.setSingleStep(5)
        self.preSlider_2.setPageStep(5)
        self.preSlider_2.setTracking(False)
        self.preSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.preSlider_2.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.preSlider_2.setObjectName(_fromUtf8("preSlider_2"))
        self.DurationSliders_2.addWidget(self.preSlider_2)
        self.rinSlider_2 = QtGui.QSlider(self.sessionslidersLayout)
        self.rinSlider_2.setMaximum(90)
        self.rinSlider_2.setSingleStep(5)
        self.rinSlider_2.setPageStep(5)
        self.rinSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.rinSlider_2.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.rinSlider_2.setObjectName(_fromUtf8("rinSlider_2"))
        self.DurationSliders_2.addWidget(self.rinSlider_2)
        self.kyoSlider_2 = QtGui.QSlider(self.sessionslidersLayout)
        self.kyoSlider_2.setMaximum(90)
        self.kyoSlider_2.setSingleStep(5)
        self.kyoSlider_2.setPageStep(5)
        self.kyoSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.kyoSlider_2.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.kyoSlider_2.setObjectName(_fromUtf8("kyoSlider_2"))
        self.DurationSliders_2.addWidget(self.kyoSlider_2)
        self.tohSlider_2 = QtGui.QSlider(self.sessionslidersLayout)
        self.tohSlider_2.setMaximum(90)
        self.tohSlider_2.setSingleStep(5)
        self.tohSlider_2.setPageStep(5)
        self.tohSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.tohSlider_2.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.tohSlider_2.setObjectName(_fromUtf8("tohSlider_2"))
        self.DurationSliders_2.addWidget(self.tohSlider_2)
        self.shaSlider_2 = QtGui.QSlider(self.sessionslidersLayout)
        self.shaSlider_2.setMaximum(90)
        self.shaSlider_2.setSingleStep(5)
        self.shaSlider_2.setPageStep(5)
        self.shaSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.shaSlider_2.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.shaSlider_2.setObjectName(_fromUtf8("shaSlider_2"))
        self.DurationSliders_2.addWidget(self.shaSlider_2)
        self.kaiSlider_2 = QtGui.QSlider(self.sessionslidersLayout)
        self.kaiSlider_2.setMaximum(90)
        self.kaiSlider_2.setSingleStep(5)
        self.kaiSlider_2.setPageStep(5)
        self.kaiSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.kaiSlider_2.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.kaiSlider_2.setObjectName(_fromUtf8("kaiSlider_2"))
        self.DurationSliders_2.addWidget(self.kaiSlider_2)
        self.jinSlider_2 = QtGui.QSlider(self.sessionslidersLayout)
        self.jinSlider_2.setMaximum(90)
        self.jinSlider_2.setSingleStep(5)
        self.jinSlider_2.setPageStep(5)
        self.jinSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.jinSlider_2.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.jinSlider_2.setObjectName(_fromUtf8("jinSlider_2"))
        self.DurationSliders_2.addWidget(self.jinSlider_2)
        self.retsuSlider_2 = QtGui.QSlider(self.sessionslidersLayout)
        self.retsuSlider_2.setMaximum(90)
        self.retsuSlider_2.setSingleStep(5)
        self.retsuSlider_2.setPageStep(5)
        self.retsuSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.retsuSlider_2.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.retsuSlider_2.setObjectName(_fromUtf8("retsuSlider_2"))
        self.DurationSliders_2.addWidget(self.retsuSlider_2)
        self.zaiSlider_2 = QtGui.QSlider(self.sessionslidersLayout)
        self.zaiSlider_2.setMaximum(90)
        self.zaiSlider_2.setSingleStep(5)
        self.zaiSlider_2.setPageStep(5)
        self.zaiSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.zaiSlider_2.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.zaiSlider_2.setObjectName(_fromUtf8("zaiSlider_2"))
        self.DurationSliders_2.addWidget(self.zaiSlider_2)
        self.zenSlider_2 = QtGui.QSlider(self.sessionslidersLayout)
        self.zenSlider_2.setMaximum(90)
        self.zenSlider_2.setSingleStep(5)
        self.zenSlider_2.setPageStep(5)
        self.zenSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.zenSlider_2.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.zenSlider_2.setObjectName(_fromUtf8("zenSlider_2"))
        self.DurationSliders_2.addWidget(self.zenSlider_2)
        self.postSlider_2 = QtGui.QSlider(self.sessionslidersLayout)
        self.postSlider_2.setMaximum(90)
        self.postSlider_2.setSingleStep(5)
        self.postSlider_2.setPageStep(5)
        self.postSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.postSlider_2.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.postSlider_2.setObjectName(_fromUtf8("postSlider_2"))
        self.DurationSliders_2.addWidget(self.postSlider_2)
        self.toptotalsLabel = QtGui.QLabel(self.frame)
        self.toptotalsLabel.setGeometry(QtCore.QRect(280, 40, 221, 21))
        self.toptotalsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.toptotalsLabel.setObjectName(_fromUtf8("toptotalsLabel"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.frame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 590, 721, 41))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.CutDurationDisplays_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.CutDurationDisplays_2.setMargin(0)
        self.CutDurationDisplays_2.setObjectName(_fromUtf8("CutDurationDisplays_2"))
        self.preDisplay_2 = QtGui.QLCDNumber(self.horizontalLayoutWidget_2)
        self.preDisplay_2.setSmallDecimalPoint(False)
        self.preDisplay_2.setNumDigits(2)
        self.preDisplay_2.setObjectName(_fromUtf8("preDisplay_2"))
        self.CutDurationDisplays_2.addWidget(self.preDisplay_2)
        self.rinDisplay_2 = QtGui.QLCDNumber(self.horizontalLayoutWidget_2)
        self.rinDisplay_2.setNumDigits(2)
        self.rinDisplay_2.setObjectName(_fromUtf8("rinDisplay_2"))
        self.CutDurationDisplays_2.addWidget(self.rinDisplay_2)
        self.kyoDisplay_2 = QtGui.QLCDNumber(self.horizontalLayoutWidget_2)
        self.kyoDisplay_2.setNumDigits(2)
        self.kyoDisplay_2.setObjectName(_fromUtf8("kyoDisplay_2"))
        self.CutDurationDisplays_2.addWidget(self.kyoDisplay_2)
        self.tohDisplay_2 = QtGui.QLCDNumber(self.horizontalLayoutWidget_2)
        self.tohDisplay_2.setNumDigits(2)
        self.tohDisplay_2.setObjectName(_fromUtf8("tohDisplay_2"))
        self.CutDurationDisplays_2.addWidget(self.tohDisplay_2)
        self.shaDisplay_2 = QtGui.QLCDNumber(self.horizontalLayoutWidget_2)
        self.shaDisplay_2.setNumDigits(2)
        self.shaDisplay_2.setObjectName(_fromUtf8("shaDisplay_2"))
        self.CutDurationDisplays_2.addWidget(self.shaDisplay_2)
        self.kaiDisplay_2 = QtGui.QLCDNumber(self.horizontalLayoutWidget_2)
        self.kaiDisplay_2.setNumDigits(2)
        self.kaiDisplay_2.setObjectName(_fromUtf8("kaiDisplay_2"))
        self.CutDurationDisplays_2.addWidget(self.kaiDisplay_2)
        self.jinDisplay_2 = QtGui.QLCDNumber(self.horizontalLayoutWidget_2)
        self.jinDisplay_2.setNumDigits(2)
        self.jinDisplay_2.setObjectName(_fromUtf8("jinDisplay_2"))
        self.CutDurationDisplays_2.addWidget(self.jinDisplay_2)
        self.retsuDisplay_2 = QtGui.QLCDNumber(self.horizontalLayoutWidget_2)
        self.retsuDisplay_2.setNumDigits(2)
        self.retsuDisplay_2.setObjectName(_fromUtf8("retsuDisplay_2"))
        self.CutDurationDisplays_2.addWidget(self.retsuDisplay_2)
        self.zaiDisplay_2 = QtGui.QLCDNumber(self.horizontalLayoutWidget_2)
        self.zaiDisplay_2.setNumDigits(2)
        self.zaiDisplay_2.setObjectName(_fromUtf8("zaiDisplay_2"))
        self.CutDurationDisplays_2.addWidget(self.zaiDisplay_2)
        self.zenDisplay_2 = QtGui.QLCDNumber(self.horizontalLayoutWidget_2)
        self.zenDisplay_2.setNumDigits(2)
        self.zenDisplay_2.setObjectName(_fromUtf8("zenDisplay_2"))
        self.CutDurationDisplays_2.addWidget(self.zenDisplay_2)
        self.postDisplay_2 = QtGui.QLCDNumber(self.horizontalLayoutWidget_2)
        self.postDisplay_2.setNumDigits(2)
        self.postDisplay_2.setObjectName(_fromUtf8("postDisplay_2"))
        self.CutDurationDisplays_2.addWidget(self.postDisplay_2)
        self.verticalLayoutWidget = QtGui.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(790, 80, 91, 561))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.totalprogressLabels = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.totalprogressLabels.setMargin(0)
        self.totalprogressLabels.setObjectName(_fromUtf8("totalprogressLabels"))
        self.rintotalLabel = QtGui.QLabel(self.verticalLayoutWidget)
        self.rintotalLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rintotalLabel.setObjectName(_fromUtf8("rintotalLabel"))
        self.totalprogressLabels.addWidget(self.rintotalLabel)
        self.kyototalLabel = QtGui.QLabel(self.verticalLayoutWidget)
        self.kyototalLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.kyototalLabel.setObjectName(_fromUtf8("kyototalLabel"))
        self.totalprogressLabels.addWidget(self.kyototalLabel)
        self.tohtotalLabel = QtGui.QLabel(self.verticalLayoutWidget)
        self.tohtotalLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tohtotalLabel.setObjectName(_fromUtf8("tohtotalLabel"))
        self.totalprogressLabels.addWidget(self.tohtotalLabel)
        self.shatotalLabel = QtGui.QLabel(self.verticalLayoutWidget)
        self.shatotalLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.shatotalLabel.setObjectName(_fromUtf8("shatotalLabel"))
        self.totalprogressLabels.addWidget(self.shatotalLabel)
        self.kaitotalLabel = QtGui.QLabel(self.verticalLayoutWidget)
        self.kaitotalLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.kaitotalLabel.setObjectName(_fromUtf8("kaitotalLabel"))
        self.totalprogressLabels.addWidget(self.kaitotalLabel)
        self.jintotalLabel = QtGui.QLabel(self.verticalLayoutWidget)
        self.jintotalLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.jintotalLabel.setObjectName(_fromUtf8("jintotalLabel"))
        self.totalprogressLabels.addWidget(self.jintotalLabel)
        self.retsutotalLabel = QtGui.QLabel(self.verticalLayoutWidget)
        self.retsutotalLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.retsutotalLabel.setObjectName(_fromUtf8("retsutotalLabel"))
        self.totalprogressLabels.addWidget(self.retsutotalLabel)
        self.zaitotalLabel = QtGui.QLabel(self.verticalLayoutWidget)
        self.zaitotalLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.zaitotalLabel.setObjectName(_fromUtf8("zaitotalLabel"))
        self.totalprogressLabels.addWidget(self.zaitotalLabel)
        self.zentotalLabel = QtGui.QLabel(self.verticalLayoutWidget)
        self.zentotalLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.zentotalLabel.setObjectName(_fromUtf8("zentotalLabel"))
        self.totalprogressLabels.addWidget(self.zentotalLabel)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(880, 80, 66, 561))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.totaldaysLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.totaldaysLayout.setMargin(0)
        self.totaldaysLayout.setObjectName(_fromUtf8("totaldaysLayout"))
        self.rintotaldaysDisplay = QtGui.QLCDNumber(self.verticalLayoutWidget_2)
        self.rintotaldaysDisplay.setObjectName(_fromUtf8("rintotaldaysDisplay"))
        self.totaldaysLayout.addWidget(self.rintotaldaysDisplay)
        self.kyototaldaysDisplay = QtGui.QLCDNumber(self.verticalLayoutWidget_2)
        self.kyototaldaysDisplay.setObjectName(_fromUtf8("kyototaldaysDisplay"))
        self.totaldaysLayout.addWidget(self.kyototaldaysDisplay)
        self.tohtotaldaysDisplay = QtGui.QLCDNumber(self.verticalLayoutWidget_2)
        self.tohtotaldaysDisplay.setObjectName(_fromUtf8("tohtotaldaysDisplay"))
        self.totaldaysLayout.addWidget(self.tohtotaldaysDisplay)
        self.shatotaldaysDisplay = QtGui.QLCDNumber(self.verticalLayoutWidget_2)
        self.shatotaldaysDisplay.setObjectName(_fromUtf8("shatotaldaysDisplay"))
        self.totaldaysLayout.addWidget(self.shatotaldaysDisplay)
        self.kaitotaldaysDisplay = QtGui.QLCDNumber(self.verticalLayoutWidget_2)
        self.kaitotaldaysDisplay.setObjectName(_fromUtf8("kaitotaldaysDisplay"))
        self.totaldaysLayout.addWidget(self.kaitotaldaysDisplay)
        self.jintotaldaysDisplay = QtGui.QLCDNumber(self.verticalLayoutWidget_2)
        self.jintotaldaysDisplay.setObjectName(_fromUtf8("jintotaldaysDisplay"))
        self.totaldaysLayout.addWidget(self.jintotaldaysDisplay)
        self.retsutotaldaysDisplay = QtGui.QLCDNumber(self.verticalLayoutWidget_2)
        self.retsutotaldaysDisplay.setObjectName(_fromUtf8("retsutotaldaysDisplay"))
        self.totaldaysLayout.addWidget(self.retsutotaldaysDisplay)
        self.zaitotaldaysDisplay = QtGui.QLCDNumber(self.verticalLayoutWidget_2)
        self.zaitotaldaysDisplay.setObjectName(_fromUtf8("zaitotaldaysDisplay"))
        self.totaldaysLayout.addWidget(self.zaitotaldaysDisplay)
        self.zentotaldaysDisplay = QtGui.QLCDNumber(self.verticalLayoutWidget_2)
        self.zentotaldaysDisplay.setObjectName(_fromUtf8("zentotaldaysDisplay"))
        self.totaldaysLayout.addWidget(self.zentotaldaysDisplay)
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.frame)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(950, 80, 55, 561))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.totaldaysLabels = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.totaldaysLabels.setMargin(0)
        self.totaldaysLabels.setObjectName(_fromUtf8("totaldaysLabels"))
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.totaldaysLabels.addWidget(self.label_6)
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.totaldaysLabels.addWidget(self.label_5)
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.totaldaysLabels.addWidget(self.label_4)
        self.label_7 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.totaldaysLabels.addWidget(self.label_7)
        self.label_9 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.totaldaysLabels.addWidget(self.label_9)
        self.label_8 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.totaldaysLabels.addWidget(self.label_8)
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.totaldaysLabels.addWidget(self.label_3)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.totaldaysLabels.addWidget(self.label_2)
        self.label = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.totaldaysLabels.addWidget(self.label)
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.frame)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(1010, 80, 66, 561))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.totalhoursLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.totalhoursLayout.setMargin(0)
        self.totalhoursLayout.setObjectName(_fromUtf8("totalhoursLayout"))
        self.rintotalhoursDisplay = QtGui.QLCDNumber(self.verticalLayoutWidget_4)
        self.rintotalhoursDisplay.setObjectName(_fromUtf8("rintotalhoursDisplay"))
        self.totalhoursLayout.addWidget(self.rintotalhoursDisplay)
        self.kyototalhoursDisplay = QtGui.QLCDNumber(self.verticalLayoutWidget_4)
        self.kyototalhoursDisplay.setObjectName(_fromUtf8("kyototalhoursDisplay"))
        self.totalhoursLayout.addWidget(self.kyototalhoursDisplay)
        self.tohtotalhoursDisplay = QtGui.QLCDNumber(self.verticalLayoutWidget_4)
        self.tohtotalhoursDisplay.setObjectName(_fromUtf8("tohtotalhoursDisplay"))
        self.totalhoursLayout.addWidget(self.tohtotalhoursDisplay)
        self.shatotalhoursDisplay = QtGui.QLCDNumber(self.verticalLayoutWidget_4)
        self.shatotalhoursDisplay.setObjectName(_fromUtf8("shatotalhoursDisplay"))
        self.totalhoursLayout.addWidget(self.shatotalhoursDisplay)
        self.kaitotalhoursDisplay = QtGui.QLCDNumber(self.verticalLayoutWidget_4)
        self.kaitotalhoursDisplay.setObjectName(_fromUtf8("kaitotalhoursDisplay"))
        self.totalhoursLayout.addWidget(self.kaitotalhoursDisplay)
        self.jintotalhoursDisplay = QtGui.QLCDNumber(self.verticalLayoutWidget_4)
        self.jintotalhoursDisplay.setObjectName(_fromUtf8("jintotalhoursDisplay"))
        self.totalhoursLayout.addWidget(self.jintotalhoursDisplay)
        self.retsutotalhoursDisplay = QtGui.QLCDNumber(self.verticalLayoutWidget_4)
        self.retsutotalhoursDisplay.setObjectName(_fromUtf8("retsutotalhoursDisplay"))
        self.totalhoursLayout.addWidget(self.retsutotalhoursDisplay)
        self.zaitotalhoursDisplay = QtGui.QLCDNumber(self.verticalLayoutWidget_4)
        self.zaitotalhoursDisplay.setObjectName(_fromUtf8("zaitotalhoursDisplay"))
        self.totalhoursLayout.addWidget(self.zaitotalhoursDisplay)
        self.zentotalhoursDisplay = QtGui.QLCDNumber(self.verticalLayoutWidget_4)
        self.zentotalhoursDisplay.setObjectName(_fromUtf8("zentotalhoursDisplay"))
        self.totalhoursLayout.addWidget(self.zentotalhoursDisplay)
        self.verticalLayoutWidget_5 = QtGui.QWidget(self.frame)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(1080, 80, 55, 561))
        self.verticalLayoutWidget_5.setObjectName(_fromUtf8("verticalLayoutWidget_5"))
        self.totalhoursLabels = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.totalhoursLabels.setMargin(0)
        self.totalhoursLabels.setObjectName(_fromUtf8("totalhoursLabels"))
        self.label_11 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.totalhoursLabels.addWidget(self.label_11)
        self.label_14 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.totalhoursLabels.addWidget(self.label_14)
        self.label_15 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.totalhoursLabels.addWidget(self.label_15)
        self.label_18 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.totalhoursLabels.addWidget(self.label_18)
        self.label_17 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.totalhoursLabels.addWidget(self.label_17)
        self.label_16 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.totalhoursLabels.addWidget(self.label_16)
        self.label_13 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.totalhoursLabels.addWidget(self.label_13)
        self.label_12 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.totalhoursLabels.addWidget(self.label_12)
        self.label_10 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.totalhoursLabels.addWidget(self.label_10)
        self.verticalLayoutWidget_6 = QtGui.QWidget(self.frame)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(1140, 80, 66, 561))
        self.verticalLayoutWidget_6.setObjectName(_fromUtf8("verticalLayoutWidget_6"))
        self.totalminutesLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_6)
        self.totalminutesLayout.setMargin(0)
        self.totalminutesLayout.setObjectName(_fromUtf8("totalminutesLayout"))
        self.rintotalminutesDisplay = QtGui.QLCDNumber(self.verticalLayoutWidget_6)
        self.rintotalminutesDisplay.setObjectName(_fromUtf8("rintotalminutesDisplay"))
        self.totalminutesLayout.addWidget(self.rintotalminutesDisplay)
        self.kyototalminutesDisplay = QtGui.QLCDNumber(self.verticalLayoutWidget_6)
        self.kyototalminutesDisplay.setObjectName(_fromUtf8("kyototalminutesDisplay"))
        self.totalminutesLayout.addWidget(self.kyototalminutesDisplay)
        self.tohtotalminutesDisplay = QtGui.QLCDNumber(self.verticalLayoutWidget_6)
        self.tohtotalminutesDisplay.setObjectName(_fromUtf8("tohtotalminutesDisplay"))
        self.totalminutesLayout.addWidget(self.tohtotalminutesDisplay)
        self.shatotalminutesDisplay = QtGui.QLCDNumber(self.verticalLayoutWidget_6)
        self.shatotalminutesDisplay.setObjectName(_fromUtf8("shatotalminutesDisplay"))
        self.totalminutesLayout.addWidget(self.shatotalminutesDisplay)
        self.kaitotalminutesDisplay = QtGui.QLCDNumber(self.verticalLayoutWidget_6)
        self.kaitotalminutesDisplay.setObjectName(_fromUtf8("kaitotalminutesDisplay"))
        self.totalminutesLayout.addWidget(self.kaitotalminutesDisplay)
        self.jintotalminutesDisplay = QtGui.QLCDNumber(self.verticalLayoutWidget_6)
        self.jintotalminutesDisplay.setObjectName(_fromUtf8("jintotalminutesDisplay"))
        self.totalminutesLayout.addWidget(self.jintotalminutesDisplay)
        self.retsutotalminutesDisplay = QtGui.QLCDNumber(self.verticalLayoutWidget_6)
        self.retsutotalminutesDisplay.setObjectName(_fromUtf8("retsutotalminutesDisplay"))
        self.totalminutesLayout.addWidget(self.retsutotalminutesDisplay)
        self.zaitotalminutesDisplay = QtGui.QLCDNumber(self.verticalLayoutWidget_6)
        self.zaitotalminutesDisplay.setObjectName(_fromUtf8("zaitotalminutesDisplay"))
        self.totalminutesLayout.addWidget(self.zaitotalminutesDisplay)
        self.zentotalminutesDisplay = QtGui.QLCDNumber(self.verticalLayoutWidget_6)
        self.zentotalminutesDisplay.setObjectName(_fromUtf8("zentotalminutesDisplay"))
        self.totalminutesLayout.addWidget(self.zentotalminutesDisplay)
        self.verticalLayoutWidget_7 = QtGui.QWidget(self.frame)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(1210, 80, 71, 561))
        self.verticalLayoutWidget_7.setObjectName(_fromUtf8("verticalLayoutWidget_7"))
        self.totaldaysLayout_6 = QtGui.QVBoxLayout(self.verticalLayoutWidget_7)
        self.totaldaysLayout_6.setMargin(0)
        self.totaldaysLayout_6.setObjectName(_fromUtf8("totaldaysLayout_6"))
        self.label_19 = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.totaldaysLayout_6.addWidget(self.label_19)
        self.label_23 = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.totaldaysLayout_6.addWidget(self.label_23)
        self.label_22 = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.totaldaysLayout_6.addWidget(self.label_22)
        self.label_21 = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.totaldaysLayout_6.addWidget(self.label_21)
        self.label_25 = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.totaldaysLayout_6.addWidget(self.label_25)
        self.label_20 = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.totaldaysLayout_6.addWidget(self.label_20)
        self.label_26 = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.totaldaysLayout_6.addWidget(self.label_26)
        self.label_24 = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.totaldaysLayout_6.addWidget(self.label_24)
        self.label_27 = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.totaldaysLayout_6.addWidget(self.label_27)
        self.horizontalLayoutWidget_6 = QtGui.QWidget(self.frame)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(790, 19, 491, 70))
        self.horizontalLayoutWidget_6.setObjectName(_fromUtf8("horizontalLayoutWidget_6"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.topsessionLabel = QtGui.QLabel(self.horizontalLayoutWidget_6)
        self.topsessionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.topsessionLabel.setObjectName(_fromUtf8("topsessionLabel"))
        self.horizontalLayout.addWidget(self.topsessionLabel)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pushButton = QtGui.QPushButton(self.horizontalLayoutWidget_6)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_3 = QtGui.QPushButton(self.horizontalLayoutWidget_6)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.verticalLayout.addWidget(self.pushButton_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayoutWidget = QtGui.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(70, 730, 291, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.AmbienceOption = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.AmbienceOption.setObjectName(_fromUtf8("AmbienceOption"))
        self.horizontalLayout_2.addWidget(self.AmbienceOption)
        self.ReferebceDisplayOption = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.ReferebceDisplayOption.setObjectName(_fromUtf8("ReferebceDisplayOption"))
        self.horizontalLayout_2.addWidget(self.ReferebceDisplayOption)
        self.gridLayoutWidget = QtGui.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(390, 720, 351, 72))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.actionsbuttonsLayout = QtGui.QHBoxLayout()
        self.actionsbuttonsLayout.setObjectName(_fromUtf8("actionsbuttonsLayout"))
        self.CreateButton = QtGui.QPushButton(self.gridLayoutWidget)
        self.CreateButton.setObjectName(_fromUtf8("CreateButton"))
        self.actionsbuttonsLayout.addWidget(self.CreateButton)
        self.exportButton = QtGui.QPushButton(self.gridLayoutWidget)
        self.exportButton.setObjectName(_fromUtf8("exportButton"))
        self.actionsbuttonsLayout.addWidget(self.exportButton)
        self.gridLayout.addLayout(self.actionsbuttonsLayout, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.PlayButton = QtGui.QPushButton(self.gridLayoutWidget)
        self.PlayButton.setObjectName(_fromUtf8("PlayButton"))
        self.horizontalLayout_3.addWidget(self.PlayButton)
        self.pushButton_2 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayoutWidget_7 = QtGui.QWidget(self.frame)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(790, 740, 491, 41))
        self.horizontalLayoutWidget_7.setObjectName(_fromUtf8("horizontalLayoutWidget_7"))
        self.goalButtonsLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.goalButtonsLayout.setMargin(0)
        self.goalButtonsLayout.setObjectName(_fromUtf8("goalButtonsLayout"))
        self.setgoalButton = QtGui.QPushButton(self.horizontalLayoutWidget_7)
        self.setgoalButton.setObjectName(_fromUtf8("setgoalButton"))
        self.goalButtonsLayout.addWidget(self.setgoalButton)
        self.goalpacingButton = QtGui.QPushButton(self.horizontalLayoutWidget_7)
        self.goalpacingButton.setObjectName(_fromUtf8("goalpacingButton"))
        self.goalButtonsLayout.addWidget(self.goalpacingButton)
        self.viewgoalsButton = QtGui.QPushButton(self.horizontalLayoutWidget_7)
        self.viewgoalsButton.setObjectName(_fromUtf8("viewgoalsButton"))
        self.goalButtonsLayout.addWidget(self.viewgoalsButton)
        self.completedgoalsButton = QtGui.QPushButton(self.horizontalLayoutWidget_7)
        self.completedgoalsButton.setObjectName(_fromUtf8("completedgoalsButton"))
        self.goalButtonsLayout.addWidget(self.completedgoalsButton)
        self.horizontalLayoutWidget_8 = QtGui.QWidget(self.frame)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(390, 650, 271, 51))
        self.horizontalLayoutWidget_8.setObjectName(_fromUtf8("horizontalLayoutWidget_8"))
        self.totalsessiondisplayLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.totalsessiondisplayLayout.setMargin(0)
        self.totalsessiondisplayLayout.setObjectName(_fromUtf8("totalsessiondisplayLayout"))
        self.totalhoursDisplay = QtGui.QLCDNumber(self.horizontalLayoutWidget_8)
        self.totalhoursDisplay.setObjectName(_fromUtf8("totalhoursDisplay"))
        self.totalsessiondisplayLayout.addWidget(self.totalhoursDisplay)
        self.totalhoursLabel = QtGui.QLabel(self.horizontalLayoutWidget_8)
        self.totalhoursLabel.setObjectName(_fromUtf8("totalhoursLabel"))
        self.totalsessiondisplayLayout.addWidget(self.totalhoursLabel)
        self.totalMinutesDisplay = QtGui.QLCDNumber(self.horizontalLayoutWidget_8)
        self.totalMinutesDisplay.setObjectName(_fromUtf8("totalMinutesDisplay"))
        self.totalsessiondisplayLayout.addWidget(self.totalMinutesDisplay)
        self.totalminutesLabel = QtGui.QLabel(self.horizontalLayoutWidget_8)
        self.totalminutesLabel.setObjectName(_fromUtf8("totalminutesLabel"))
        self.totalsessiondisplayLayout.addWidget(self.totalminutesLabel)
        self.calculateTotalSessionTimeButton = QtGui.QPushButton(self.frame)
        self.calculateTotalSessionTimeButton.setGeometry(QtCore.QRect(160, 670, 201, 23))
        self.calculateTotalSessionTimeButton.setObjectName(_fromUtf8("calculateTotalSessionTimeButton"))
        self.layoutWidget = QtGui.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(790, 640, 491, 101))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.goalsVLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.goalsVLayout.setMargin(0)
        self.goalsVLayout.setObjectName(_fromUtf8("goalsVLayout"))
        self.goallabelsLayout = QtGui.QHBoxLayout()
        self.goallabelsLayout.setObjectName(_fromUtf8("goallabelsLayout"))
        self.currenttopLabel = QtGui.QLabel(self.layoutWidget)
        self.currenttopLabel.setStyleSheet(_fromUtf8("border-top: 1px solid black;\n"
"border-left: 1px solid black;\n"
"border-right: 1px solid black;"))
        self.currenttopLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.currenttopLabel.setObjectName(_fromUtf8("currenttopLabel"))
        self.goallabelsLayout.addWidget(self.currenttopLabel)
        self.progresstopLabel = QtGui.QLabel(self.layoutWidget)
        self.progresstopLabel.setMinimumSize(QtCore.QSize(290, 0))
        self.progresstopLabel.setStyleSheet(_fromUtf8("border-top: 1px solid black;"))
        self.progresstopLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.progresstopLabel.setObjectName(_fromUtf8("progresstopLabel"))
        self.goallabelsLayout.addWidget(self.progresstopLabel)
        self.goaltopLabel = QtGui.QLabel(self.layoutWidget)
        self.goaltopLabel.setStyleSheet(_fromUtf8("border-top: 1px solid black;\n"
"border-right: 1px solid black;\n"
"border-left: 1px solid black;"))
        self.goaltopLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.goaltopLabel.setObjectName(_fromUtf8("goaltopLabel"))
        self.goallabelsLayout.addWidget(self.goaltopLabel)
        self.goalsVLayout.addLayout(self.goallabelsLayout)
        self.goalactualLayout = QtGui.QHBoxLayout()
        self.goalactualLayout.setObjectName(_fromUtf8("goalactualLayout"))
        self.currentgoalLabel = QtGui.QLabel(self.layoutWidget)
        self.currentgoalLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.currentgoalLabel.setBaseSize(QtCore.QSize(0, 0))
        self.currentgoalLabel.setStyleSheet(_fromUtf8("border-left: 1px solid black;\n"
"border-bottom: 1px solid black;\n"
"border-right: 1px solid black;"))
        self.currentgoalLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.currentgoalLabel.setMargin(0)
        self.currentgoalLabel.setObjectName(_fromUtf8("currentgoalLabel"))
        self.goalactualLayout.addWidget(self.currentgoalLabel)
        self.goalProgressBar = QtGui.QProgressBar(self.layoutWidget)
        self.goalProgressBar.setProperty("value", 24)
        self.goalProgressBar.setObjectName(_fromUtf8("goalProgressBar"))
        self.goalactualLayout.addWidget(self.goalProgressBar)
        self.goalLabel = QtGui.QLabel(self.layoutWidget)
        self.goalLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.goalLabel.setStyleSheet(_fromUtf8("border-right: 1px solid black;\n"
"border-left: 1px solid black;\n"
"border-bottom: 1px solid black;"))
        self.goalLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.goalLabel.setObjectName(_fromUtf8("goalLabel"))
        self.goalactualLayout.addWidget(self.goalLabel)
        self.goalsVLayout.addLayout(self.goalactualLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1300, 30))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuTools = QtGui.QMenu(self.menuBar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpen_Session = QtGui.QAction(MainWindow)
        self.actionOpen_Session.setObjectName(_fromUtf8("actionOpen_Session"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionCheck_Integrity = QtGui.QAction(MainWindow)
        self.actionCheck_Integrity.setObjectName(_fromUtf8("actionCheck_Integrity"))
        self.actionAbout_This_Program = QtGui.QAction(MainWindow)
        self.actionAbout_This_Program.setObjectName(_fromUtf8("actionAbout_This_Program"))
        self.actionAbout_Qt = QtGui.QAction(MainWindow)
        self.actionAbout_Qt.setObjectName(_fromUtf8("actionAbout_Qt"))
        self.menuFile.addAction(self.actionOpen_Session)
        self.menuFile.addAction(self.actionExit)
        self.menuTools.addAction(self.actionCheck_Integrity)
        self.menuHelp.addAction(self.actionAbout_This_Program)
        self.menuHelp.addAction(self.actionAbout_Qt)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuTools.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.PlayButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.statusBar.clearMessage)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.preLabel_2.setText(_translate("MainWindow", "PRE", None))
        self.rinLabel_2.setText(_translate("MainWindow", "RIN", None))
        self.kyoLabel_2.setText(_translate("MainWindow", "KYO", None))
        self.tohLabel_2.setText(_translate("MainWindow", "TOH", None))
        self.shaLabel_2.setText(_translate("MainWindow", "SHA", None))
        self.kaiLabel_2.setText(_translate("MainWindow", "KAI", None))
        self.jinLabel_2.setText(_translate("MainWindow", "JIN", None))
        self.retsuLabel_2.setText(_translate("MainWindow", "RETSU", None))
        self.zaiLabel_2.setText(_translate("MainWindow", "ZAI", None))
        self.zenLabel_2.setText(_translate("MainWindow", "ZEN", None))
        self.postLabel_2.setText(_translate("MainWindow", "POST", None))
        self.toptotalsLabel.setText(_translate("MainWindow", "THIS SESSION", None))
        self.rintotalLabel.setText(_translate("MainWindow", "RIN", None))
        self.kyototalLabel.setText(_translate("MainWindow", "KYO", None))
        self.tohtotalLabel.setText(_translate("MainWindow", "TOH", None))
        self.shatotalLabel.setText(_translate("MainWindow", "SHA", None))
        self.kaitotalLabel.setText(_translate("MainWindow", "KAI", None))
        self.jintotalLabel.setText(_translate("MainWindow", "JIN", None))
        self.retsutotalLabel.setText(_translate("MainWindow", "RETSU", None))
        self.zaitotalLabel.setText(_translate("MainWindow", "ZAI", None))
        self.zentotalLabel.setText(_translate("MainWindow", "ZEN", None))
        self.label_6.setText(_translate("MainWindow", "Days", None))
        self.label_5.setText(_translate("MainWindow", "Days", None))
        self.label_4.setText(_translate("MainWindow", "Days", None))
        self.label_7.setText(_translate("MainWindow", "Days", None))
        self.label_9.setText(_translate("MainWindow", "Days", None))
        self.label_8.setText(_translate("MainWindow", "Days", None))
        self.label_3.setText(_translate("MainWindow", "Days", None))
        self.label_2.setText(_translate("MainWindow", "Days", None))
        self.label.setText(_translate("MainWindow", "Days", None))
        self.label_11.setText(_translate("MainWindow", "Hours", None))
        self.label_14.setText(_translate("MainWindow", "Hours", None))
        self.label_15.setText(_translate("MainWindow", "Hours", None))
        self.label_18.setText(_translate("MainWindow", "Hours", None))
        self.label_17.setText(_translate("MainWindow", "Hours", None))
        self.label_16.setText(_translate("MainWindow", "Hours", None))
        self.label_13.setText(_translate("MainWindow", "Hours", None))
        self.label_12.setText(_translate("MainWindow", "Hours", None))
        self.label_10.setText(_translate("MainWindow", "Hours", None))
        self.label_19.setText(_translate("MainWindow", "Minutes", None))
        self.label_23.setText(_translate("MainWindow", "Minutes", None))
        self.label_22.setText(_translate("MainWindow", "Minutes", None))
        self.label_21.setText(_translate("MainWindow", "Minutes", None))
        self.label_25.setText(_translate("MainWindow", "Minutes", None))
        self.label_20.setText(_translate("MainWindow", "Minutes", None))
        self.label_26.setText(_translate("MainWindow", "Minutes", None))
        self.label_24.setText(_translate("MainWindow", "Minutes", None))
        self.label_27.setText(_translate("MainWindow", "Minutes", None))
        self.topsessionLabel.setText(_translate("MainWindow", "TOTAL PROGRESS", None))
        self.pushButton.setText(_translate("MainWindow", "View List Of Sessions", None))
        self.pushButton_3.setText(_translate("MainWindow", "View Premature Endings", None))
        self.AmbienceOption.setText(_translate("MainWindow", "AMBIENCE", None))
        self.ReferebceDisplayOption.setText(_translate("MainWindow", "REFERENCE FILES", None))
        self.CreateButton.setText(_translate("MainWindow", "CREATE", None))
        self.exportButton.setText(_translate("MainWindow", "EXPORT", None))
        self.PlayButton.setText(_translate("MainWindow", "PLAY", None))
        self.pushButton_2.setText(_translate("MainWindow", "PAUSE", None))
        self.setgoalButton.setText(_translate("MainWindow", "Set New Goal", None))
        self.goalpacingButton.setText(_translate("MainWindow", "Goal Pacing", None))
        self.viewgoalsButton.setText(_translate("MainWindow", "Current Goals", None))
        self.completedgoalsButton.setText(_translate("MainWindow", "Completed Goals", None))
        self.totalhoursLabel.setText(_translate("MainWindow", "Hours", None))
        self.totalminutesLabel.setText(_translate("MainWindow", "Minutes", None))
        self.calculateTotalSessionTimeButton.setText(_translate("MainWindow", "Calculate Total Session Time", None))
        self.currenttopLabel.setText(_translate("MainWindow", "Current", None))
        self.progresstopLabel.setText(_translate("MainWindow", "Progress To Goal", None))
        self.goaltopLabel.setText(_translate("MainWindow", "Goal", None))
        self.currentgoalLabel.setText(_translate("MainWindow", "100 hrs", None))
        self.goalLabel.setText(_translate("MainWindow", "300 hrs", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuTools.setTitle(_translate("MainWindow", "Tools", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionOpen_Session.setText(_translate("MainWindow", "Open Session", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionCheck_Integrity.setText(_translate("MainWindow", "Check Integrity", None))
        self.actionAbout_This_Program.setText(_translate("MainWindow", "About This Program", None))
        self.actionAbout_Qt.setText(_translate("MainWindow", "About Qt", None))

